#!/bin/bash

source venv/bin/activate
pip install --upgrade -r requirements-dev.txt

# update tools
dt -q
echo "Updated tools (`dt -q -d`)"

# automatic tests
dt -q
python manage.py test
if [ "$?" != "0" ]; then
    echo "Django manage.py test reported problems, terminating release"
    exit 1
fi
echo "Django manage.py test ok (`dt -q -d`), proceeding..."

# prospector
dt -q
prospector
if [ "$?" != "0" ]; then
    echo "Prospector reported problems, terminating release"
    exit 1
fi
echo "Prospector cleared build (`dt -q -d`), proceeding..."

# mypy
mypy jutil

# pytype
# dt -q
# pytype --config pytype.cfg
# if [ "$?" != "0" ]; then
#     echo "Pytype reported problems, terminating release"
#     exit 1
# fi
# echo "Pytype cleared build (`dt -q -d`), proceeding..."

./test-coverage --codecov

exit 0
