# (generated with --quick)

import collections
from typing import Any, Type

OrderedDict: Type[collections.OrderedDict]
capfirst: Any
re: module

def _dict_to_html_format_key(k: str) -> str: ...
def _dict_to_html_r(data: dict, margin: str = ..., format_keys: bool = ...) -> str: ...
def choices_label(choices: tuple, value) -> str: ...
def dict_to_html(data: dict, format_keys: bool = ...) -> str: ...
def sorted_dict(d: dict) -> collections.OrderedDict: ...
