# (generated with --quick)

from typing import Any

HttpRequest: Any
get_real_ip: Any
logger: logging.Logger
logging: module
settings: Any
timezone: module
traceback: module

class ActivateUserProfileTimezone:
    __doc__: str
    def __call__(self, request) -> Any: ...
    def __init__(self, get_response = ...) -> None: ...
    def get_response(self, _1) -> Any: ...

class EnsureLanguageCookieMiddleware:
    __doc__: str
    def __call__(self, request) -> Any: ...
    def __init__(self, get_response = ...) -> None: ...
    def get_response(self, _1) -> Any: ...

class EnsureOriginMiddleware:
    __doc__: str
    def __call__(self, request) -> Any: ...
    def __init__(self, get_response = ...) -> None: ...
    def get_response(self, _1) -> Any: ...

class LogExceptionMiddleware:
    __doc__: str
    def __call__(self, request) -> Any: ...
    def __init__(self, get_response = ...) -> None: ...
    def get_response(self, _1) -> Any: ...
    def process_exception(self, request, e) -> None: ...

def send_email(recipients: list, subject: str, text: str = ..., html: str = ..., sender: str = ..., files: list = ..., cc_recipients: list = ..., bcc_recipients: list = ..., exceptions: bool = ...) -> Any: ...
