# (generated with --quick)

from typing import Any, List, Tuple

Model: Any
force_text: Any

def choices_label(choices: tuple, value) -> str: ...
def clone_model(instance, cls: type = ..., commit: bool = ..., exclude_fields: tuple = ..., base_class_suffix: str = ..., **kw) -> Any: ...
def get_model_field_label_and_value(instance, field_name: str) -> Tuple[str, str]: ...
def get_model_keys(instance, cls: type = ..., exclude_fields: tuple = ..., base_class_suffix: str = ...) -> List[str]: ...
def get_object_or_none(cls, **kwargs) -> Any: ...
def is_model_field_changed(instance, field_name: str) -> bool: ...
