# (generated with --quick)

from typing import Any, Tuple

def _split_obj_attr_path(obj, key: str, exceptions: bool = ...) -> Tuple[Any, str]: ...
def get_obj_attr(obj, key: str, default = ..., exceptions: bool = ...) -> Any: ...
def set_obj_attr(obj, key: str, val) -> None: ...
